### ISSUE TITLE
Color inconsistences

### ISSUE THREAD

**Issue by aggalex** [basjam/ValaCompiler#16]
The application has color inconsistencies all over it's window. Perhaps you would like to try granite's `SettingsSidebar` or use the widget `Gtk.separator (orientation=Gtk.Orientation.HORIZONTAL);`/`Gtk.separator (orientation=Gtk.Orientation.VERTICAL);` or even use a CSS style sheet to apply the same color everywhere (the hard way).

**Comment by basjam** [comment]
I am very inexperienced in both UI designing and programming. Therefore, for the time being, I don't think I'll go the CSS route. I'm not sure I understand where exactly the colour inconsistencies occur, and also where are the separators needed? Any clarification is really appreciated. 

Thanks for your interest in the project.

**Comment by aggalex** [comment]
Sorry for answering late, didn't have the opportunity to.
Each red circle with a number on the screenshot below is a UI design problem.
1. White on the left, light gray to the right. Both colors are used as light background colors. That's a color inconsistency.
2. Bad layout, can make your UI look cluttered and uncomfortable.
3. Badly separated sections, resulting in uncertain separation. Also makes UI look cluttered.

![valacompiler-projectpage screenshot png](https://user-images.githubusercontent.com/11951328/35883396-cd0952b6-0b8f-11e8-8bc5-35e4bdca24f8.png)

**Comment by basjam** [comment]
I updated the ProjectPage ui by adding separators around options side panel.
so for:
1- The difference in colour is intentional to indicate the Files list area.
2 & 3 - moved CheckButtons to the top to avoid clutter. And used separators all around options menu.

![valacompiler-projectpage screenshot png](https://raw.githubusercontent.com/basjam/ValaCompiler/master/screenshots/ValaCompiler-ProjectPage(ScreenShot).png)

**Comment by aggalex** [comment]
Perfect job!!! The only suggestion is to give a little bit more padding/margin to the options checkboxes and your design will be perfect! But so far so good! Keep it up!

**Comment by basjam** [comment]
1.0.1 had a redesign that addresses this issue. 
Closing.
