### ISSUE TITLE
A re-compile button aside from the regular buttons in header

### ISSUE THREAD

**Issue by surajmandalcell** [basjam/ValaCompiler#24]
As you can see there are only two option to start and stop process, to recompile i have to manually go back and press compile again which after 50 times gets annoying.
Please add a re-compile option at top and perhaps consider using static title instead of huge line of path as title.
![image](https://user-images.githubusercontent.com/11650177/40580215-0eb2938a-6158-11e8-9d91-ba5f9ab381c6.png)

**Comment by basjam** [comment]
Also I fixed this in the update/rewrite. Uploading soon.

**Comment by surajmandalcell** [comment]
nice!

**Comment by surajmandalcell** [comment]
Issue closed
