### ISSUE TITLE
The welcome window is too big

### ISSUE THREAD

**Issue by surajmandalcell** [basjam/ValaCompiler#25]
![image](https://user-images.githubusercontent.com/11650177/40584649-2c2ed7ec-61c2-11e8-9137-f4de2f1b3eae.png)

**Comment by surajmandalcell** [comment]
Almost same issue with another elementary os vala app https://github.com/alcadica/develop/commit/4028067afa81ffb671a9955385e6d317ef78151d

**Comment by basjam** [comment]
I'll leave this issue open because I'm working on a huge update/rewrite that I didn't upload yet. I'll apply your fix after.

Thanks.

**Comment by surajmandalcell** [comment]
closing
