### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by brigazvi** [basjam/ValaCompiler#30]
![bitmap](https://user-images.githubusercontent.com/37640970/42270865-87e9bdbe-7f8a-11e8-8194-95d9c12b7d0c.png)

@basjam Which one do you like more?

**Comment by basjam** [comment]
I like the second one. I think it is more unique and easier to recognize.

Is it possible to make the "V" similar to the one used in valadoc? That was the main element for me when designing the logo for this app.
![banana](https://raw.githubusercontent.com/Valadoc/valadoc-org/master/data/images/icon.png)

**Comment by brigazvi** [comment]
@basjam Second attempt:
![rect3959](https://user-images.githubusercontent.com/37640970/42451662-92677574-8390-11e8-8682-ef102be81973.png)
![rect3958](https://user-images.githubusercontent.com/37640970/42451663-92d38b24-8390-11e8-8a21-fac9ba2d4e6e.png)

**Comment by basjam** [comment]
I like both of them. I prefer the white one as the app icon, I think it will fits better with the standard theme of both elementary and GNOME.

However, When the dark mode is added to the app, I think the dark Icon will fit better.

**Comment by brigazvi** [comment]
@basjam I created a [pull request](https://github.com/basjam/ValaCompiler/pull/32).
