### ISSUE TITLE
[Support] Where am I going wrong?

### ISSUE THREAD

**Issue by btd1337** [basjam/ValaCompiler#34]
Could you tell me what I'm doing wrong?

![screenshot from 2018-07-17 03-14-41](https://user-images.githubusercontent.com/11943860/42799879-e2a17df2-896f-11e8-8b32-53c5d4935058.png)

![screenshot from 2018-07-17 03-15-04](https://user-images.githubusercontent.com/11943860/42799886-e6d1362e-896f-11e8-9b2d-ab1db3dadebd.png)

![screenshot from 2018-07-17 03-15-32](https://user-images.githubusercontent.com/11943860/42799894-ea596316-896f-11e8-8227-09b09ce7e8cc.png)

**Comment by basjam** [comment]
you must use double dash ( -- ) before "pkg". As it is, it is looking for files called "pkg=...".

This stems from the way 'valac' works.


Let me know if it works so I could close.

**Comment by btd1337** [comment]
Thank you for your help! It worked!
